.github/workflows/analysis.yml

---
- [Frontend](https://sustainment-capstone-2024-4-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://sustainment-capstone-2024-4-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis Workflow](https://github.com/bcgov/sustainment-capstone-2024/actions/workflows/analysis.yml)
- [Merge Workflow](https://github.com/bcgov/sustainment-capstone-2024/actions/workflows/merge.yml)

ci: swith to default CodeQL workflow

---

.github/workflows/analysis.yml
frontend/Dockerfile

---
- [Frontend](https://sustainment-capstone-2024-1-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://sustainment-capstone-2024-1-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis Workflow](https://github.com/bcgov/sustainment-capstone-2024/actions/workflows/analysis.yml)
- [Merge Workflow](https://github.com/bcgov/sustainment-capstone-2024/actions/workflows/merge.yml)

chore: Update Dockerfile

---

charts/app/values.yaml

---
- [Frontend](https://nr-sustainment-capstone-2024-5-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-5-frontend.apps.silver.devops.gov.bc.ca/api)

fix(ci): reduce replicas

---

charts/app/templates/backend/templates/deployment.yaml

---
- [Frontend](https://nr-sustainment-capstone-2024-6-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-6-frontend.apps.silver.devops.gov.bc.ca/api)

fix(ci): dial down initContainers resources

---

.github/codeowners

include `localnewstv` and `fergmac` to codeowners
---
- [Frontend](https://nr-sustainment-capstone-2024-12-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-12-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): Update codeowners pre-capstone students

---

.github/workflows/pr-close.yml

---
- [Frontend](https://nr-sustainment-capstone-2024-14-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-14-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): temporarly disable pr-close.yml

---

.github/ISSUE_TEMPLATE/Task.md

- Add task template to our repository
---
- [Frontend](https://nr-sustainment-capstone-2024-16-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-16-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): [NMP-15] FEATURE** Add task template

---

.github/codeowners

Update Codeowners to Capstone Students
---
- [Frontend](https://nr-sustainment-capstone-2024-18-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-18-frontend.apps.silver.devops.gov.bc.ca/api)

feat(ci): [NMP-17] FEATURE** update codeowners

---

.github/codeowners

- Correcting codeowners to re-add previously removed members
- Miscommunication led to removal
---
- [Frontend](https://nr-sustainment-capstone-2024-21-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-21-frontend.apps.silver.devops.gov.bc.ca/api)

fix: [NMP-N/A] update codeowners re-adding users, correct username

---

docker-compose.yml

---
- [Frontend](https://nr-sustainment-capstone-2024-33-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-33-frontend.apps.silver.devops.gov.bc.ca/api)

feat(ci): [NMP-20] Feature** Setup Docker-compose

---

.github/ISSUE_TEMPLATE/Schoolwork.md

Created an issue template for schoolwork
---
- [Frontend](https://nr-sustainment-capstone-2024-38-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-38-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): [NMP-37] Feature** Created a schoolwork issue template for organization

---

.github/pull_request_template.md
docker-compose.yml

Removed Test Category, type of changes, and checklist remains the same. 
Will edit again after team review agreement.
---
- [Frontend](https://nr-sustainment-capstone-2024-34-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-34-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): [NMP-31] creating pull request template

---

.github/ISSUE_TEMPLATE/Bugs.md

Created an issue template for bugs so it is easy to create a bug ticket easier.
---
- [Frontend](https://nr-sustainment-capstone-2024-42-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-42-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): [NMP-32] Feature** Created an issue template for bugs

---

database/db/entrypoint/01-initseed.sql
docker-compose.yml

Created a seed for the database inside the docker containers. 
Considering creating another pr to tackle the warning database "admin" does not exists.
---
- [Frontend](https://nr-sustainment-capstone-2024-57-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-57-frontend.apps.silver.devops.gov.bc.ca/api)

feat(ci): [NMP-24] Feature** created a seed for database, and added volumes for data persistency

---

.github/codeowners

Add Sustainment Team member to codeowners file
---
- [Frontend](https://nr-sustainment-capstone-2024-66-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-66-frontend.apps.silver.devops.gov.bc.ca/api)

fix: [NMP-N/A] Update codeowners

---

README.md
backend/README.md
frontend/README.md

Updated root, backend and frontend readme files to make it easy to start growing them incrementally.
---
- [Frontend](https://nr-sustainment-capstone-2024-76-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-76-frontend.apps.silver.devops.gov.bc.ca/api)

docs: Nmp 70 update readme

---

.github/workflows/pr-close.yml
.github/workflows/pr-open.yml

---
- [Frontend](https://nr-sustainment-capstone-2024-86-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-86-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-sustainment-capstone-2024/actions/wor …

chore(ci): Uncommented PR pipeline openshift cues

---

.github/workflows/.deploy.yml
.github/workflows/pr-open.yml
database/Dockerfile
database/openshift.deploy.yml
docker-compose.yml

Start moving to OpenShift.  Database is task number 1.
---
- [Frontend](https://nr-sustainment-capstone-2024-111-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-111-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): adjust docker compose and deploy database to openshift

---

.github/workflows/.deploy.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
backend/Dockerfile
backend/openshift.deploy.yml
database/openshift.deploy.yml
docker-compose.yml

- backend template and deployment
- image promotions on pr close
- CMD envar for docker-compose testing (e.g. `CMD=serve docker compose up`)
---
- [Frontend](https://nr-sustainment-capstone-2024-118-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-118-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): backend openshift deployment

---

.github/workflows/.deploy.yml
backend/Dockerfile
backend/openshift.deploy.yml
docker-compose.yml
frontend/Dockerfile
frontend/openshift.deploy.yml

---
- [Frontend](https://nr-sustainment-capstone-2024-119-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-119-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): frontend openshift deployment

---

backend/README.md
frontend/README.md

Updated nmp to better berries as team discussion.
---
- [Frontend](https://nr-sustainment-capstone-2024-121-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-121-frontend.apps.silver.devops.gov.bc.ca/api)

chore: [BB-92] chore** updated nmp to better berries in docs

---

docker-compose.yml
frontend/Dockerfile

Updated docker-compose.yml to fix hot-reloading. 
Docker compose watch path was trying to update the wrong dir in the container.
For the frontend, there was an error about the user not having a passwd/ not having permission to change the files in the container.
error:
```bash
WARN[0040] Error handling changed files for service frontend: 1 error occurred:
* copying files to 8b249dff25aa513a429657b89feb6ff0d3d070d850eddbd7e683da7522771e7d: Error response from daemon: getent unable to find entry "1011540000" in passwd database
```
Fix testing:
---
- [Frontend](https://nr-sustainment-capstone-2024-130-frontend.apps.silver.devops.gov.bc.ca)
- …

fix(ci): Bb 129 fix hot reloading in frontendbackend

---

frontend/src/App.tsx
frontend/src/Commons/Button.tsx
frontend/src/Commons/Styles/Button.style.tsx

Created a Button Component
Responsiveness of the Button will not be tested here. it will be tested on the ticket for the Landing Page
---
- [Frontend](https://nr-sustainment-capstone-2024-134-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-134-frontend.apps.silver.devops.gov.bc.ca/api)
---
Deployments, as …

feat: [BB-103] Feature** created a Button Component

---

.github/workflows/pr-validate.yml
backend/Dockerfile
backend/openshift.deploy.yml
backend/src/db.ts
charts/app/templates/frontend/templates/deployment.yaml
docker-compose.yml
frontend/openshift.deploy.yml

Explicitly import database vars, hopefully fixing out backend crash.  Also added a console debug for db client when LOG_LEVEL !== info.
---
- [Frontend](https://nr-sustainment-capstone-2024-162-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-162-backend.apps.silver.devops.gov.bc.ca/api/health)

chore(ci): troubleshoot backend

---

frontend/src/Commons/Button/Button.style.ts
frontend/src/Commons/Footer/Footer.tsx
frontend/src/Commons/Forms/FormModule/FormModule.tsx
frontend/src/Commons/Forms/InputModules/Calculate/Calculate.tsx
frontend/src/Commons/Forms/InputModules/FarmInformation/FarmInformation.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsAndSoil.tsx
frontend/src/Commons/Forms/InputModules/ManureAndCompost/ManureAndCompost.tsx
frontend/src/Commons/Forms/InputModules/Summary/Summary.tsx
frontend/src/Interface/InputModuleinterface.tsx

Enhance InputModules to use a long and short name.
Now you can choose which to render depending on `@mediaQuery`
---
- [Frontend](https://nr-sustainment-capstone-2024-175-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-175-backend.apps.silver.devops.gov.bc.ca/api/health)

chore: Bb 174 enhance inputmodules to have short and long names

---

backend/openshift.deploy.yml

Removed defined secrets that refers to 161 pull request.
---
- [Frontend](https://nr-sustainment-capstone-2024-185-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-185-backend.apps.silver.devops.gov.bc.ca/api/health)

fix: removed defined 161 secret

---

frontend/src/Commons/Button/Button.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsAndSoil.tsx
frontend/src/Commons/Forms/InputModules/Summary/Summary.tsx
frontend/src/Commons/MainPageHeader/MainPageHeader.tsx
frontend/src/Commons/ProgressBar/ProgressBar.styles.ts
frontend/src/Constants/InitialFarmDetails.ts
frontend/src/Interface/FarmDetailsInterface.tsx
frontend/src/Interface/FieldDetailsInterface.tsx
frontend/src/Views/Export/ExportPage.tsx
frontend/src/Views/LandingPage/LandingPage.styles.ts
frontend/src/Views/LandingPage/LandingPage.tsx
frontend/src/Views/MainPage/MainPage.styles.ts
frontend/src/Views/MainPage/MainPage.tsx

Now when clicking the Load button, we can select an `.nmp` file and all relevant information to BetterBerries should be loaded into BetterBerries own `farmDetails`, the apps main Data Object.
There is a very crude Summary implemented so we can see this the `farmDetails` data. It's still to be properly implemented. 
The file is uploaded on the LandingPage, where it gets stored as a string. It then, redirects the user to the MainPage.
In the MainPage, localStorage is checked for a `farmDetails` object. This is set up so we can have a modal asking if the user wants to continue a past calculation when he clicks the `New Calculation` Button.
When the user exports his data, `localStorage` gets cleaned up and the `continue last calc` will not happen. This behaviour is to be implemented in …

feat: Bb 155 load nmp files

---

frontend/src/Commons/MainPageHeader/MainPageHeader.styles.ts
frontend/src/Commons/ProgressBar/ProgressBar.styles.ts
frontend/src/Views/MainPage/MainPage.styles.ts

Followed through the ticket that LocalNewsTV has created. Tested it myself, probably got fixed from earlier merges.
Feel free to test it out again! I've self reviewed, just moved form module a little bit higher as there's a lot of spaces from the progress bar and the form module itself.
---
- [Frontend](https://nr-sustainment-capstone-2024-202-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-202-backend.apps.silver.devops.gov.bc.ca/api/health)
After merge, new images are …

fix: [BB-195] FIX** ProgressBar Position Fix

---

frontend/src/Commons/Forms/FormHeader/FormHeader.tsx
frontend/src/Commons/Forms/FormModule/FormModule.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsAndSoil.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsButtonComponent.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsListComponent.tsx
frontend/src/Interface/InputModuleProps.tsx
frontend/src/Views/MainPage/MainPage.tsx

Created a Back Button so there is a user-friendly option to go back to the form instead of only using the form header as a way to go back and go forward to the form.
> Given that I press back on the Field and Soil Form Module it will redirect me to Farm Information Module
from:
to:
Note that this pull request doesn't include storing user inputs into local storage. So whenever going back to field and soil form module it will display the input fields first then will still show the earlier list that was inputted. It will be implemented on the future sprint.
---
- [Frontend](https://nr-sustainment-capstone-2024-203-frontend.apps.silver.devops.gov.bc.ca)
- …

feat: [BB-189] Feature** implemented back button

---

frontend/src/Commons/CustomLink/CustomLink.style.ts
frontend/src/Commons/Forms/FormHeader/FormHeader.tsx
frontend/src/Commons/Forms/FormModule/FormModule.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsButtonComponent.tsx
frontend/src/Interface/nmpInterface.tsx
frontend/src/Views/Export/ExportPage.tsx
frontend/src/Views/LandingPage/LandingPage.tsx
frontend/src/Views/MainPage/MainPage.tsx

You can now download an nmp file by clicking the export button. So far, only FarmName and Year variable are available for edditing inside BetterBerries. It will be expanded in the future.
Export functionality demo:
---
- [Frontend](https://nr-sustainment-capstone-2024-206-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-206-backend.apps.silver.devops.gov.bc.ca/api/health)
- [Merge …

feat: Bb 150 implement exporting json to nmp

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml
backend/openshift.deploy.yml
database/openshift.deploy.yml
frontend/Dockerfile
frontend/openshift.deploy.yml

Set up a prod-like environment.  Our next stop is usually TEST.  If required we can just plain rename it PROD.  :P
---
- [Frontend](https://nr-sustainment-capstone-2024-204-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-204-backend.apps.silver.devops.gov.bc.ca/api/health)

feat(ci): set up prod-like environment

---

.github/workflows/merge.yml

...whoops...
---
- [Frontend](https://nr-sustainment-capstone-2024-209-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-209-backend.apps.silver.devops.gov.bc.ca/api/health)

fix(ci): merge triggers

---

.github/workflows/merge.yml

Still at it.
---
- [Frontend](https://nr-sustainment-capstone-2024-210-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-210-backend.apps.silver.devops.gov.bc.ca/api/health)

fix(ci): merge deps

---

.github/codeowners

Add @dallascrichmond  to codeowners
---
- [Frontend](https://nr-sustainment-capstone-2024-226-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-226-backend.apps.silver.devops.gov.bc.ca/api/health)
- [Merge …

chore: Update codeowners

---

frontend/src/Commons/Button/Button.style.ts
frontend/src/Commons/CustomLink/CustomLink.style.ts
frontend/src/Commons/Forms/InputModules/FarmInformation/FarmInformation.style.ts
frontend/src/Commons/Forms/InputModules/FarmInformation/FarmInformation.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsAndSoil.style.ts
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsAndSoil.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsButtonComponent.styles.ts
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsButtonComponent.tsx
frontend/src/Commons/MainPageFooter/MainPageFooter.styles.ts
frontend/src/Commons/ProgressBar/ProgressBar.styles.ts
frontend/src/Views/LandingPage/LandingPage.tsx
frontend/src/Views/MainPage/MainPage.tsx

---
- [Frontend](https://nr-sustainment-capstone-2024-224-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-224-backend.apps.silver.devops.gov.bc.ca/api/health)
- [Merge Workflow](https://github.com/bcgov/nr-sustainment-capstone-2024/act …

chore: [BB-223] mockups alignment

---

frontend/src/Commons/Forms/FormHeader/FormHeader.style.ts
frontend/src/Commons/Forms/FormHeader/FormHeader.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsAndSoil.style.ts
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsAndSoil.tsx
frontend/src/Views/Export/ExportPage.styles.ts
frontend/src/Views/Export/ExportPage.tsx

Fixed missHeading through project. Now Headers are in order, being properly used.
---
- [Frontend](https://nr-sustainment-capstone-2024-238-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-238-backend.apps.silver.devops.gov.bc.ca/api/health)

fix: Fixed missHeading and basic header styling

---

.github/workflows/.deploy.yml

It hurts to live!  How could the letter `s` have made our lives so difficult?!!
---
- [Frontend](https://nr-sustainment-capstone-2024-286-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-286-backend.apps.silver.devops.gov.bc.ca/api/health)

fix(ci): frontend overwrite settings

---

frontend/src/Commons/Button/FieldButtonGroup.styles.ts

button centered
---
- [Frontend](https://nr-sustainment-capstone-2024-289-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-289-backend.apps.silver.devops.gov.bc.ca/api/health)

fix: button centered

---

frontend/src/Commons/Button/FieldButtonGroup.styles.ts
frontend/src/Commons/FormStyles.styles.ts
frontend/src/Commons/Forms/InputModules/Calculation/Calculation.tsx
frontend/src/Commons/Forms/InputModules/Calculation/CalculationList.styles.ts
frontend/src/Commons/Forms/InputModules/Calculation/CalculationList.tsx
frontend/src/Commons/Forms/InputModules/Crops/CropsInfo.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsAndSoil.tsx
frontend/src/Commons/InformationIcons/InformationIcons.styles.ts
frontend/src/Commons/InformationIcons/InformationIcons.tsx
frontend/src/Commons/Input/Field/CustomField.style.ts
frontend/src/Commons/Input/Field/CustomField.tsx
frontend/src/Commons/Input/Select/CustomSelect.style.ts
frontend/src/Commons/Input/Select/CustomSelect.tsx

Implemented the Information Icons and added them into the forms like where it was in the mockups. Text are from NMP Application.
> [!NOTE]
> This is not 100% exact copy of what's in the mockup.
---
- [Frontend](https://nr-sustainment-capstone-2024-302-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-302-backend.apps.silver.devops.gov.bc.ca/api/health)
- [Merge Workflow](https://github.com/bcgov/nr-sustainment-capstone-2024/actions/wor …

feat: [BB-293] Feature** icons done and assigned

---

frontend/openshift.deploy.yml

---
- [Frontend](https://nr-sustainment-capstone-2024-304-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-304-backend.apps.silver.devops.gov.bc.ca/api/health)
- [Merge Workflow](https://github.com/bcgov/nr-sustainment-capstone-2024/act …

feat(ci): shorten route URL

---

frontend/src/Commons/FormStyles.styles.ts
frontend/src/Commons/Forms/FormModule/FormModule.tsx
frontend/src/Commons/Forms/InputModules/Calculation/Calculation.tsx
frontend/src/Commons/Forms/InputModules/Calculation/CalculationList.styles.ts
frontend/src/Commons/Forms/InputModules/Calculation/CalculationList.tsx
frontend/src/Commons/Forms/InputModules/Crops/CropsInfo.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsAndSoil.tsx
frontend/src/Commons/InformationIcons/InformationIcons.styles.ts
frontend/src/Commons/InformationIcons/InformationIcons.tsx
frontend/src/Commons/Input/Field/CustomField.style.ts
frontend/src/Commons/Input/Field/CustomField.tsx
frontend/src/Commons/Input/Select/CustomSelect.style.ts
frontend/src/Commons/Input/Select/CustomSelect.tsx
frontend/src/Commons/MainPageFooter/MainPageFooter.styles.ts
frontend/src/Commons/MainPageFooter/MainPageFooter.tsx
frontend/src/Commons/MainPageHeader/MainPageHeader.styles.ts
frontend/src/Commons/MainPageHeader/MainPageHeader.tsx
frontend/src/Commons/Toggle/Toggle.styles.ts
frontend/src/Commons/Toggle/Toggle.tsx
frontend/src/Constants/ToggleText.ts
frontend/src/Interface/InputModuleProps.tsx
frontend/src/Views/MainPage/MainPage.tsx

Created a toggle that uses a state hook in the MainPage and use that as a main source of truth to every children that uses InformationIcon and Toggle components.
Given that toggle is true, all the information icons inside MainPage will be displayed:none, otherwise, appear.
No Mockups, but based on agreement of the team here's the behaviour
https://github.com/user-attachments/assets/8ae92088-64a0-4ba7-ba7f-01cc36c8b785
Also, manually created an inverted version of the bubbles. flex doesn't work since the items inside are dynamically changing so I have to resort to manual positioning.
---
- [Frontend](https://nr-sustainment-capstone-2024-306-frontend.apps.silver.devops.gov.bc.ca …

feat: [BB-294] FEATURE** toggle implementation

---

frontend/src/Commons/ProgressBar/ProgressBar.styles.ts

added max-width to the Container so the line doesn't cut through the ProgressBar Items.
Previous Behaviour:
Current Behaviour after changes:
https://github.com/user-attachments/assets/3c9fa6b6-8eb0-48c0-a3f2-a7f3b7c52e09
---
- [Frontend](https://nr-sustainment-capstone-2024-307-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-307-backend.apps.silver.devops.gov.bc.ca/api/health)
- [Merge …

fix: [BB-305] FIX** added max-width for ProgressBar

---

frontend/src/Commons/Button/Button.style.ts
frontend/src/Commons/Button/ButtonSizeConstant.ts
frontend/src/Commons/Forms/FormModule/FormModule.style.ts
frontend/src/Commons/Forms/InputModules/FarmInformation/FarmInformation.style.ts

fix the button style for the farm information and also aligned the sizing of the buttons further with the mockups that the designer made.
---
- [Frontend](https://nr-sustainment-capstone-2024-308-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-308-backend.apps.silver.devops.gov.bc.ca/api/health)

fix: button styles

---

frontend/src/Commons/Button/FieldButtonGroup.styles.ts
frontend/src/Commons/FormStyles.styles.ts
frontend/src/Commons/Forms/FormHeader/FormHeader.tsx
frontend/src/Commons/Forms/FormModule/FormModule.style.ts
frontend/src/Commons/Forms/FormModule/FormModule.tsx
frontend/src/Commons/Forms/InputModules/Crops/CropsInfo.tsx
frontend/src/Commons/Forms/InputModules/FarmInformation/FarmInformation.style.ts
frontend/src/Commons/Forms/InputModules/Fertilizers/Fertilizers.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsListComponent.tsx
frontend/src/Commons/Forms/InputModules/ListComponent.styles.ts
frontend/src/Commons/MainPageFooter/MainPageFooter.styles.ts
frontend/src/Commons/MainPageFooter/MainPageFooter.tsx
frontend/src/Commons/MainPageHeader/MainPageHeader.styles.ts
frontend/src/Commons/MainPageHeader/MainPageHeader.tsx
frontend/src/Commons/ProgressBar/ProgressBar.styles.ts
frontend/src/Commons/ProgressBar/ProgressBar.tsx
frontend/src/Views/MainPage/MainPage.styles.ts
frontend/src/Views/MainPage/MainPage.tsx

broken down stylings cleanup to fix some minor details in the web application. 
> [!NOTE]
> If you see some more minor details, I'm working on it on the next pr.
---
- [Frontend](https://nr-sustainment-capstone-2024-316-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-316-backend.apps.silver.devops.gov.bc.ca/api/health)

fix: [BB-314] FIX/Feature** styling fixes stage 1

---

frontend/src/Commons/Button/Button.style.ts
frontend/src/Commons/Button/Button.tsx
frontend/src/Commons/Footer/Footer.style.ts
frontend/src/Commons/FormStyles.styles.ts
frontend/src/Commons/Forms/FormModule/FormModule.style.ts
frontend/src/Commons/Forms/FormModule/FormModule.tsx
frontend/src/Commons/Forms/InputModules/CalculateNutrients/CalculateNutrients.tsx
frontend/src/Commons/Forms/InputModules/Crops/CropsInfo.tsx
frontend/src/Commons/Forms/InputModules/FarmInformation/FarmInformation.style.ts
frontend/src/Commons/Forms/InputModules/FarmInformation/FarmInformation.tsx
frontend/src/Commons/Forms/InputModules/Fertilizers/Fertilizers.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsAndSoil.tsx
frontend/src/Commons/Input/Field/CustomField.style.ts
frontend/src/Commons/Input/Field/CustomField.tsx
frontend/src/Commons/Input/Select/CustomSelect.style.ts
frontend/src/Commons/Input/Select/CustomSelect.tsx
frontend/src/Commons/Input/TextArea/CustomTextArea.styles.ts
frontend/src/Commons/Input/TextArea/CustomTextArea.tsx
frontend/src/Commons/LandingPageHeader/LandingPageHeader.style.tsx
frontend/src/Commons/MainPageHeader/MainPageHeader.styles.ts
frontend/src/Commons/ProgressBar/ProgressBar.styles.ts
frontend/src/Commons/ProgressItem/ProgressItem.styles.ts
frontend/src/Views/LandingPage/LandingPage.styles.ts
frontend/src/Views/LandingPage/LandingPage.tsx
frontend/src/Views/MainPage/MainPage.styles.ts

Primarily, fixed stylings for Landing Page, Farm Information Module, and the components that are inside it too, to make it **EXACTLY** as it is from mockup. Designer already had a look and gave a thumbs up with the changes inside. 
Please check the code, and let me know if there's a simpler way of doing it. Thanks!
---
- [Frontend](https://nr-sustainment-capstone-2024-323-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-323-backend.apps.silver.devops.gov.bc.ca/api/health) …

fix: [BB-318] FIX** stylings cleanup stage2 [LANDING PAGE, FARMINFO]

---

frontend/src/Commons/Forms/FormModule/FormModule.tsx
frontend/src/Commons/Forms/InputModules/CalculateNutrients/CalculateNutrients.tsx
frontend/src/Commons/Forms/InputModules/Crops/CropsInfo.tsx
frontend/src/Commons/Forms/InputModules/FarmInformation/FarmInformation.tsx
frontend/src/Commons/Forms/InputModules/Fertilizers/FertilizersButtonComponent.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsAndSoil.tsx
frontend/src/Interface/InputModuleProps.tsx
frontend/src/Views/MainPage/MainPage.tsx

Straightoforward changes that fix weird Next button behaivour.
> Clicking on the next button moves the form forward no matter the condition.
Clicking the next button closes the current form and opens the next one. If the next button is clicked on a previously filled out form, it only updates the data and closes it's form section, which is different then a forward movement in the forms.
If the user is working on form section 3 and he clicks on the next button on the form section 1, section 3 would close and open section 4. 
If the user is working on form section 3 and he clicks on the next button on the form section 1, section 3 is not affected and section 1 closes. 
---
- …

chore: Enhance Next button behaviour

---

frontend/src/Commons/Forms/InputModules/CalculateNutrients/CalculateNutrients.tsx
frontend/src/Commons/Forms/InputModules/CalculateNutrients/CalculateNutrientsButtonGroup.tsx
frontend/src/Commons/Forms/InputModules/Crops/CropsButtonGroup.tsx
frontend/src/Commons/Forms/InputModules/Fertilizers/Fertilizers.tsx
frontend/src/Commons/Forms/InputModules/Fertilizers/FertilizersButtonComponent.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsButtonComponent.tsx
frontend/src/Constants/LocalStorageNames.ts
frontend/src/Constants/ModuleIDs.ts
frontend/src/Utils/getLocalDetails.ts
frontend/src/Utils/getLocalFertilizers.ts
frontend/src/Utils/getLocalFormStates.ts
frontend/src/Views/Export/ExportPage.tsx
frontend/src/Views/LandingPage/LandingPage.tsx
frontend/src/Views/MainPage/MainPage.tsx

Updated the back button to behave more like the next button after it's update.
Also changed Names to LocalStorageNames, just so it's more descriptive. Minor cleanup.
---
- [Frontend](https://nr-sustainment-capstone-2024-331-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-331-backend.apps.silver.devops.gov.bc.ca/api/health)

chore: Bb 330 update back button to match new next button behaviour

---

frontend/src/Commons/Forms/InputModules/Crops/CropsInfo.styles.ts
frontend/src/Commons/Forms/InputModules/Crops/CropsInfo.tsx
frontend/src/Constants/CropOptions.ts
frontend/src/Utils/Calculate/calculation-data/blueberryCalculation.json

Selecting plants and rows distances return the crop density now.
---
- [Frontend](https://nr-sustainment-capstone-2024-329-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-329-backend.apps.silver.devops.gov.bc.ca/api/health)

chore: Update distance relationship to plants per acre

---

frontend/src/Commons/Button/FieldButtonGroup.styles.ts
frontend/src/Commons/Forms/InputModules/CalculateNutrients/CalculateNutrientsList.styles.ts
frontend/src/Commons/Forms/InputModules/CalculateNutrients/CalculateNutrientsList.tsx
frontend/src/Commons/Forms/InputModules/ListComponent.styles.ts

---
- [Frontend](https://nr-sustainment-capstone-2024-340-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-340-backend.apps.silver.devops.gov.bc.ca/api/health)
- [Merge Workflow](https://github.com/bcgov/nr-sustainment-capstone-2024/act …

chore: Bb 290 restructure calculate nutrients for mobile first

---

frontend/src/Commons/Button/Button.style.ts
frontend/src/Commons/Button/Button.tsx
frontend/src/Commons/Button/ButtonSizeConstant.ts
frontend/src/Commons/Button/FieldButtonGroup.styles.ts
frontend/src/Commons/CustomLink/CustomLink.style.ts
frontend/src/Commons/FormStyles.styles.ts
frontend/src/Commons/Forms/FormModule/FormModule.style.ts
frontend/src/Commons/Forms/InputModules/CalculateNutrients/CalculateNutrientsList.tsx
frontend/src/Commons/Forms/InputModules/Crops/CropsButtonGroup.tsx
frontend/src/Commons/Forms/InputModules/Crops/CropsInfo.styles.ts
frontend/src/Commons/Forms/InputModules/Crops/CropsList.styles.ts
frontend/src/Commons/Forms/InputModules/FarmInformation/FarmInformation.style.ts
frontend/src/Commons/Forms/InputModules/Fertilizers/Fertilizers.styles.ts
frontend/src/Commons/Forms/InputModules/Fertilizers/Fertilizers.tsx
frontend/src/Commons/Forms/InputModules/Fertilizers/FertilizersButtonComponent.tsx
frontend/src/Commons/Forms/InputModules/Fertilizers/FertilizersListComponent.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsAndSoil.tsx
frontend/src/Commons/Forms/InputModules/ListComponent.styles.ts
frontend/src/Commons/Input/Field/CustomField.style.ts
frontend/src/Commons/Input/Field/CustomField.tsx
frontend/src/Commons/MainPageFooter/MainPageFooter.styles.ts
frontend/src/Commons/ProgressBar/ProgressBar.styles.ts

Fixed Fertilizers form styling, and a bit of  the document discrepancies that the designer gave me.
---
- [Frontend](https://nr-sustainment-capstone-2024-341-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-341-backend.apps.silver.devops.gov.bc.ca/api/health)

fix: [BB-339] FIX** fertilizers form module styling fixes

---

frontend/src/Commons/CustomLink/CustomLink.style.ts
frontend/src/Commons/Forms/InputModules/CalculateNutrients/CalculateNutrients.styles.ts
frontend/src/Commons/Forms/InputModules/CalculateNutrients/CalculateNutrientsList.styles.ts
frontend/src/Commons/Forms/InputModules/CalculateNutrients/CalculateNutrientsList.tsx
frontend/src/Commons/Forms/InputModules/Crops/CropsInfo.styles.ts
frontend/src/Commons/Forms/InputModules/Crops/CropsInfo.tsx
frontend/src/Commons/Forms/InputModules/Fertilizers/Fertilizers.styles.ts
frontend/src/Commons/Forms/InputModules/Fertilizers/FertilizersListComponent.tsx
frontend/src/Commons/Forms/InputModules/FieldsAndSoil/FieldsListComponent.tsx
frontend/src/Commons/InformationIcons/InformationIcons.styles.ts

Final Styling Changes based on designer's document.
---
- [Frontend](https://nr-sustainment-capstone-2024-348-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-348-backend.apps.silver.devops.gov.bc.ca/api/health)

fix: [BB-347] FIX** final styling stretch
